# -*- coding: utf-8 -*-
"""RANDOM PASSWORD GENERATOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1houoxbI6ZTNdTMADybpdZ88ALbyy2crl
"""

import random
import string

print('hello, Welcome to Password generator!')

length = int(input('Enter the length of password: '))

lower = string.ascii_lowercase
upper = string.ascii_uppercase
num = string.digits
symbols = string.punctuation

all = lower + upper + num + symbols

temp = random.sample(all,length)
password = "".join(temp)

all = string.ascii_letters + string.digits + string.punctuation
password = "".join(random.sample(all,length))

print(password)